webtalk_init -webtalk_dir D:/EnglishStandardPath/Practice_File/P_DigitalLogic_H/MyProject/MyProject.sim/sim_1/behav/xsim/xsim.dir/one_track_player_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 17 21:35:36 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "be86d57b-289e-4cdd-bd97-1abcbea9927a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "62c309d2cb81459194ddbf0d5829a36c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2894 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "102828320 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15636_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3107394048 -regid "" -xml D:/EnglishStandardPath/Practice_File/P_DigitalLogic_H/MyProject/MyProject.sim/sim_1/behav/xsim/xsim.dir/one_track_player_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/EnglishStandardPath/Practice_File/P_DigitalLogic_H/MyProject/MyProject.sim/sim_1/behav/xsim/xsim.dir/one_track_player_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/EnglishStandardPath/Practice_File/P_DigitalLogic_H/MyProject/MyProject.sim/sim_1/behav/xsim/xsim.dir/one_track_player_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
